name: simply_widgets
description: Widgets created for Apparyllis
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_markdown: ^0.6.14
  flutter_stripe: ^9.2.0
  flutter_stripe_web: ^4.1.0
  intl: ^0.18.0
  markdown: ^7.0.0
  styled_widget: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
